# Generated by Django 3.0.5 on 2020-04-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_auto_20200426_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='transactions',
            new_name='savings',
        ),
        migrations.AlterField(
            model_name='account',
            name='item',
            field=models.CharField(default='', max_length=200),
        ),
    ]
